default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: s1947s1947
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: rails_boards_development

test:
  <<: *default
  database: rails_boards_test

production:
  <<: *default
  host: <%= Rails.application.secrets.DB_HOST %>
  database: <%= Rails.application.secrets.DB_NAME %>
  username: <%= Rails.application.secrets.DB_USERNAME %>
  password: <%= Rails.application.secrets.DB_PASSWORD %>